# -*- mode: ruby -*-
# vi: set ft=ruby :

API_VERSION="2"

Vagrant.configure(API_VERSION) do |config|

  vmname = "jpfds-box-%s" % Time.now.strftime("%Y%b%d-%Hh%Mm")

  # base vm configuration
  config.vm.hostname  = vmname
  config.vm.box       = "precise64"
  config.vm.box_url   = "http://files.vagrantup.com/precise64.box"
  config.vm.provider "virtualbox" do |vb|
    vb.name = vmname
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # host folder sharing
  config.vm.synced_folder "../",  "/home/vagrant/jpfds"

  config.vm.provision :shell do |s| s.path = 'init.sh' end

  config.ssh.forward_agent = true

end
